### ISSUE TITLE
Biweekly Sync Up April 3, Tuesday 2pm UTC

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#17]
Hello!

Our very first Dynamic Data and Capabilities Working Group meeting will take place tomorrow, Tuesday at 2pm UTC!

This call will be a place for everyone interested in:

> research and development of building blocks that enable collaborative applications, providing solutions for security, identity, access control, concurrency, synchronization, offline and near-real-time collaboration on top of IPFS.

to share progress, plans, discuss and pick priorities.

+ Meeting: https://protocol.zoom.us/j/586782711
+ Notes: https://cryptpad.fr/code/#/1/edit/7Rg5efVdl+CrqvAkmRqH2Q/QZH1bR6Zku7G2+F1Xn1Vxd1J/

@diasdavid has added this to [the IPFS Community Calendar](https://github.com/ipfs/community#calendar), which you can subscribe to.

See you then!

**Comment by daviddias** [comment]
@pgte is the recording uploaded?

**Comment by pgte** [comment]
Yes, it’s here: https://www.youtube.com/watch?v=vYLinVuy8fw
