### ISSUE TITLE
Biweekly Sync rescheduled

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#20]
As [requested by some](https://github.com/ipfs/research-CRDT/issues/22#issuecomment-382329276), we're moving the time for our biweekly call to 4pm GMT. This should increase the probability of people in the USA west coast to be able to join.

Next meeting will be on [May 1st, 4pm GMT](http://everytimezone.com/#2018-5-1,240,5yid).

@diasdavid could you please update the community calendar?

**Comment by daviddias** [comment]
good call. done! :)

**Comment by pgte** [comment]
Thank you!
