### ISSUE TITLE
Calendar alert

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#21]
@diasdavid Could you set up a 5 minute calendar alert (or do you consider that to be too annoying?).

**Comment by daviddias** [comment]
@pgte Alerts are personal, not a calendar thing. If you see that people are not showing up or simply missing the meeting, consider:

- Announcing it through email to the most active folks on the DDC on IPFS
- Announce it on #ipfs one hour before and then 5 mins before
- Tweet about it
- Announce it at the IPFS All Hands.
