### ISSUE TITLE
calling for volunteers to host the July 10th meeting

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#31]
Next DDC-WG meeting would be on July 10th. I can't make it, so we have two alternatives:

a) either someone volunteers to host it or
b) we postpone to the week after, which will be July 17th.

I'll wait to see if someone volunteers here before this Friday. Otherwise, I'll resolve to postpone it.

**Comment by gpestana** [comment]
@pgte I could help with this. Let me know what you think and how I can setup the call in zoom and whatnot if we hold the call on Tuesday.

**Comment by pgte** [comment]
Thank you @gpestana ! I created the respective issue, which has the zoom and pad links: https://github.com/ipfs/dynamic-data-and-capabilities/issues/32

You should be able to use zoom to record this to your local drive if you can. If you have time, please test the URL and try to record something to see if it works.
