### ISSUE TITLE
Scheduled: Dynamic Data and Capabilities WG bi-weekly meeting— July 10, 2018

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#32]
4pm GMT

Meeting: https://protocol.zoom.us/j/586782711
Notes: https://cryptpad.fr/code/#/2/code/edit/exH55BxcxISO4uOyyqVXs7vg/

Lead: @gpestana

**Comment by gpestana** [comment]
@pgte is it possible to give me host permissions? I'm getting an error when trying the recording:

<img width="437" alt="screen shot 2018-07-08 at 20 41 56" src="https://user-images.githubusercontent.com/1398860/42422888-c38176c4-82ef-11e8-8eee-f29cbed7d908.png">

I'm connected with my personal google account (g6pestana@gmail.com)

**Comment by pgte** [comment]
Unfortunately I can't seam to be able to add hosts outside of PL team. Can you host the meeting yourself, on another URL? If so let me know, and I'll change the meeting URL.
Otherwise, we'll skip recording on this one...

**Comment by gpestana** [comment]
Only me and @fritzy were present in the call and since we didn't have recording permissions, we only added the notes to [cryptpad](https://cryptpad.fr/code/#/2/code/edit/exH55BxcxISO4uOyyqVXs7vg/).

**Comment by pgte** [comment]
Ok @gpestana, thanks!

**Comment by pgte** [comment]
Notes:

----

# Dynamic Data and Capabilities WG — July 10, 2018

- **Lead:** Gonçalo Pestana (@gpestana)
- **Notetaker:** 
- **Attendees:**
	Gonçalo Pestana (@gpestana)
	Nathan Fritz @fritzy
- [**Zoom.us meeting URL**](https://protocol.zoom.us/j/586782711)
- **Recording** No recording since call didn't take place (notes below)

## Agenda

1. Start recording
1. Ask everyone to put their name into the list of attendees
1. Ask for a volunteer to take notes
1. Everyone can add items to this agenda for things they would like to discuss
1. Round of intros and updates
  - Introduce yourself and your interest in this subject
  - What have you accomplished since the last meeting?
  - Were there any blockers? If so, which ones? Is it still blocked? Why?
  - What is the next important thing you should focus on?    
1. Demos
1. Questions

### 2 Week Updates:

#### @gpestana
 - IPFS devdays @ Berlin

#### @fritzy
 - Working on https://github.com/ipfs-shipyard/peerpad-peer-crdt/ for a peerpad replacement.
 	- recent docs
  - user identity with attestation
  - based on peer-crdt rather than y.js

#### @
 - Concluded:
 - In progress:
 - Blocked:
 - Next:

### Questions

- Q: 
A: 

### Other notes
