### ISSUE TITLE
Scheduled: Dynamic Data and Capabilities WG bi-weekly meeting— July 24, 2018

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#34]
4pm GMT

Meeting: https://protocol.zoom.us/j/586782711
Notes: https://cryptpad.fr/code/#/2/code/edit/vS0KgvSUMTgHW7gbjalSHqZa/

See you there!

**Comment by satazor** [comment]
Too bad I couldn't attend due to personal affairs :(

I would have made a demo showing a TODO app being converted to a DApp :/

**Comment by pgte** [comment]
No worries, we'll do a recording of that in the next week or so :)

**Comment by pgte** [comment]
## Notes:

-----

# Dynamic Data and Capabilities WG — July 24, 2018

- **Lead:** Pedro (@pgte)
- **Notetaker:** 
- **Attendees:**
  - @mkg20001
  - @pgte
  - @gpestana
- [**Zoom.us meeting URL**](https://protocol.zoom.us/j/586782711)
- [**Recording**](https://youtu.be/x4hO-Jblfic)

## Agenda

1. Start recording
1. Ask everyone to put their name into the list of attendees
1. Ask for a volunteer to take notes
1. Everyone can add items to this agenda for things they would like to discuss
1. Round of intros and updates
  - Introduce yourself and your interest in this subject
  - What have you accomplished since the last meeting?
  - Were there any blockers? If so, which ones? Is it still blocked? Why?
  - What is the next important thing you should focus on?    
1. Demos
  - PeerPad using peer-star-app
1. Questions

### 2 Week Updates:

#### @
 - Concluded:
 - In progress:
 - Blocked:
 - Next:

#### @pgte
 - Concluded:
   - peer-star-app: encryption in transmission and at rest
 - In progress:
   - peer-star-app:
     - performance tests
     - support and general improvements
   - peer-pad
     - integrating peer-star-app in it
     - showing remote cursors and markers
 - Blocked:
 - Next:

#### @mkg20001
 - Concluded:
 - In progress:
   - Load testing for peer pad
   - Rendezvous integration
 - Blocked:
   - Bugs in load-testing after rebase
   - Libp2p chicken&egg problems (https://github.com/libp2p/js-libp2p/issues/159, https://github.com/ipfs/js-ipfs/pull/1396)
 - Next:

#### @gpestana
 - not much time allocated to DDC :(
