### ISSUE TITLE
IdentityManager v0

### ISSUE THREAD

**Issue by satazor** [ipfs/dynamic-data-and-capabilities#43]
As part of the 2018 Q4, we want to develop a initial version of the [IdentityManager](https://github.com/ipfs-shipyard/peer-star/blob/rfc-identity/docs/rfc-identity.md) to prove that the concept works and is technically possible.

- [ ] Implement a very rudimentary UI
- [ ] Implement importing uPort identities
- [ ] Implement authenticate to apps
- [ ] Implement sign (with session key)
- [ ] Implement verifySignature() which verifies a signature and checks if the key is within the DID Document

**Comment by satazor** [comment]
I will be moving this issue to the pm-idm repo.

**Comment by satazor** [comment]
@pgte It seems I don't have perm, can you do it for me?

**Comment by pgte** [comment]
@satazor done.

**Comment by pgte** [comment]
@satazor you mean transfer this issue to the pm-idm? Does GitHub allow to transfer issues between repos in different orgs?

Could you instead add an issue there and point this one to that one?

**Comment by satazor** [comment]
Yes it allows to transfer issues across projects of the same org, which is not the case :/. Will do.

**Comment by satazor** [comment]
Superseded by https://github.com/ipfs-shipyard/pm-idm/issues/2
