### ISSUE TITLE
Where can I find the notes for the Biweekly? 

### ISSUE THREAD

**Issue by daviddias** [ipfs/dynamic-data-and-capabilities#46]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/1211152/47963957-74a93400-e033-11e8-9d40-1ccc095db6a6.png">

No url is linked on the calendar event.

**Comment by pgte** [comment]
@diasdavid the notes pasted at the end of each of the meeting:
https://github.com/ipfs/dynamic-data-and-capabilities/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+meeting

Each bi-weekly has its own issue in this repo.

I suggest that the calendar event should point to https://github.com/ipfs/dynamic-data-and-capabilities/issues/36

(Unfortunately I don't think I have the capacity to change community calendar)

**Comment by daviddias** [comment]
@pgte may I recommend to submit the notes as PRs to the repo? Makes it simpler to review/comment/follow up.

@pgte added you as an admin of the community calendar with your @protocol.ai account.

**Comment by pgte** [comment]
@diasdavid thank you! Updated.
