### ISSUE TITLE
Scheduled: Dynamic Data and Capabilities WG bi-weekly meeting— December 11th, 2018

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#52]
4PM GMT

Call: https://protocol.zoom.us/j/586782711

Notes: https://dev.peerpad.net/#/w/markdown/4eiXmnC1Mkfp8T5RCXuZrqGpg3z5J9uFkc1x1wSM53DR/4XTTMAsJxQtUU8sxouPkT5HaP76ykhiLPxgA346Z2npKgKvqx-K3TgUoguYJNmW7XziGKJ15dyqekvSCpNgUX8RZ63d3THK6gGwpDQRrfeHLCTmSrBVyj9xbK84wfJBRr25i1AYnA2zYZGzwpAqVPErWnmHXmwCDD6Xx8NhVGriTK3ijV5EywMpa8z

**Comment by pgte** [comment]
Let's try and use PeerPad for this meeting.
The notes are now [here](https://dev.peerpad.net/#/w/markdown/4eiXmnC1Mkfp8T5RCXuZrqGpg3z5J9uFkc1x1wSM53DR/4XTTMAsJxQtUU8sxouPkT5HaP76ykhiLPxgA346Z2npKgKvqx-K3TgUoguYJNmW7XziGKJ15dyqekvSCpNgUX8RZ63d3THK6gGwpDQRrfeHLCTmSrBVyj9xbK84wfJBRr25i1AYnA2zYZGzwpAqVPErWnmHXmwCDD6Xx8NhVGriTK3ijV5EywMpa8z).

**Comment by satazor** [comment]
@pgte the document is empty to me, have you written something?

**Comment by pgte** [comment]
@satazor save is timing out, so it looks like the pinner is borked.. 
I'll try to keep my replica up and running for now..
