### ISSUE TITLE
Community and DDC call

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#53]
Doodle: https://doodle.com/poll/hbpe3frqae682qde

**Comment by pgte** [comment]
@mikeal @jimpick @satazor @marcooliveira @dirkmc @aschmahmann @daviddias 
Am I forgetting someone? Please tag them.

**Comment by marcooliveira** [comment]
@PedroMiguelSS, although he might have to join from the hospital. He'll let us know

**Comment by marcooliveira** [comment]
Just filled Doodle. Looking forward to this!
