### ISSUE TITLE
Scheduled: Dynamic Data and Capabilities WG weekly meeting — February 5th, 2019

### ISSUE THREAD

**Issue by pgte** [ipfs/dynamic-data-and-capabilities#72]
February 5th, 2019
4PM GMT

Call: https://protocol.zoom.us/j/586782711

Notes: https://cryptpad.fr/code/#/2/code/edit/BBvSCk3ptHq1K8EyhJUvQiTv/

**Comment by pgte** [comment]
@parkan could you lead this one?

**Comment by pgte** [comment]
@satazor can you lead the meeting today?

**Comment by satazor** [comment]
Yep I can. How will we manage zoom?

**Comment by satazor** [comment]
We are going to use this zoom instead: https://zoom.us/j/896298813

**Comment by parkan** [comment]
hi @satazor, sorry I guess I was the only one with delegated zoom access (as far as I can tell from this email -- it's in portugese 😅)

I will be prepared next week!

**Comment by satazor** [comment]
We have used @dirkmc zoom account for today’s meeting and we were able to record it as well., no worries!

**Comment by dirkmc** [comment]
é tudo de bom meu amigo
https://github.com/ipfs/dynamic-data-and-capabilities/pull/73

**Comment by parkan** [comment]
https://youtu.be/IbtMmns7sQ0 <--recording here!
